package principal;

import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    int vecSal[];

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();

        pnSintactico.setVisible(false);
        pnSemantico.setVisible(false);
        pnIntermedio.setVisible(false);
        pnOptimizacion.setVisible(false);
        pnObjeto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnContenedor = new javax.swing.JPanel();
        pnCarga1 = new javax.swing.JPanel();
        lbCargar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnGuardar = new javax.swing.JPanel();
        lbGuardar = new javax.swing.JLabel();
        pnSintactico = new javax.swing.JPanel();
        lbSintactico = new javax.swing.JLabel();
        pnSemantico = new javax.swing.JPanel();
        lbSemantico = new javax.swing.JLabel();
        pnOptimizacion = new javax.swing.JPanel();
        lbOptimizacion = new javax.swing.JLabel();
        pnIntermedio = new javax.swing.JPanel();
        lbIntermedio = new javax.swing.JLabel();
        pnLexico = new javax.swing.JPanel();
        lbLexico = new javax.swing.JLabel();
        pnObjeto = new javax.swing.JPanel();
        lbObjeto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProgramaFuente = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProgramaCompilado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCargar.setText("Cargar");
        lbCargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCargarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnCarga1Layout = new javax.swing.GroupLayout(pnCarga1);
        pnCarga1.setLayout(pnCarga1Layout);
        pnCarga1Layout.setHorizontalGroup(
            pnCarga1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCargar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        pnCarga1Layout.setVerticalGroup(
            pnCarga1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCargar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnContenedor.add(pnCarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 70, 30));

        jLabel1.setText("Programa Fuente");
        pnContenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel2.setText("Programa Compilado");
        pnContenedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        lbGuardar.setText("Guardar");
        lbGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbGuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnGuardarLayout = new javax.swing.GroupLayout(pnGuardar);
        pnGuardar.setLayout(pnGuardarLayout);
        pnGuardarLayout.setHorizontalGroup(
            pnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        pnGuardarLayout.setVerticalGroup(
            pnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnContenedor.add(pnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 70, 30));

        lbSintactico.setText("Sintactico");
        lbSintactico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSintacticoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnSintacticoLayout = new javax.swing.GroupLayout(pnSintactico);
        pnSintactico.setLayout(pnSintacticoLayout);
        pnSintacticoLayout.setHorizontalGroup(
            pnSintacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSintactico, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        pnSintacticoLayout.setVerticalGroup(
            pnSintacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSintactico, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnContenedor.add(pnSintactico, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 70, 30));

        lbSemantico.setText("Semantico");
        lbSemantico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSemanticoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnSemanticoLayout = new javax.swing.GroupLayout(pnSemantico);
        pnSemantico.setLayout(pnSemanticoLayout);
        pnSemanticoLayout.setHorizontalGroup(
            pnSemanticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSemantico, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        pnSemanticoLayout.setVerticalGroup(
            pnSemanticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSemantico, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnContenedor.add(pnSemantico, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 70, 30));

        lbOptimizacion.setText("Optimizacion");
        lbOptimizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbOptimizacionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnOptimizacionLayout = new javax.swing.GroupLayout(pnOptimizacion);
        pnOptimizacion.setLayout(pnOptimizacionLayout);
        pnOptimizacionLayout.setHorizontalGroup(
            pnOptimizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbOptimizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnOptimizacionLayout.setVerticalGroup(
            pnOptimizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbOptimizacion, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnContenedor.add(pnOptimizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 70, 30));

        lbIntermedio.setText("Intermedio");
        lbIntermedio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbIntermedioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnIntermedioLayout = new javax.swing.GroupLayout(pnIntermedio);
        pnIntermedio.setLayout(pnIntermedioLayout);
        pnIntermedioLayout.setHorizontalGroup(
            pnIntermedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbIntermedio, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        pnIntermedioLayout.setVerticalGroup(
            pnIntermedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbIntermedio, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnContenedor.add(pnIntermedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 70, 30));

        lbLexico.setText("Lexico");
        lbLexico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLexicoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnLexicoLayout = new javax.swing.GroupLayout(pnLexico);
        pnLexico.setLayout(pnLexicoLayout);
        pnLexicoLayout.setHorizontalGroup(
            pnLexicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLexico, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        pnLexicoLayout.setVerticalGroup(
            pnLexicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLexico, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnContenedor.add(pnLexico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 70, 30));

        lbObjeto.setText("Objeto");

        javax.swing.GroupLayout pnObjetoLayout = new javax.swing.GroupLayout(pnObjeto);
        pnObjeto.setLayout(pnObjetoLayout);
        pnObjetoLayout.setHorizontalGroup(
            pnObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        pnObjetoLayout.setVerticalGroup(
            pnObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnContenedor.add(pnObjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 70, 30));

        jTProgramaFuente.setColumns(20);
        jTProgramaFuente.setRows(5);
        jScrollPane1.setViewportView(jTProgramaFuente);

        pnContenedor.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 340, 180));

        jTProgramaCompilado.setColumns(20);
        jTProgramaCompilado.setRows(5);
        jScrollPane2.setViewportView(jTProgramaCompilado);

        pnContenedor.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 340, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbLexicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLexicoMouseClicked
        pnSintactico.setVisible(true);
        pnSemantico.setVisible(false);
        pnIntermedio.setVisible(false);
        pnOptimizacion.setVisible(false);
        pnObjeto.setVisible(false);
        StringTokenizer st = new StringTokenizer(jTProgramaFuente.getText(), "+-^*/();=<>{}& \n\b\r\t\",:", true);
        String texto = "";
        String cadena = "";
        while (st.hasMoreElements()) {
            cadena = st.nextToken();
            if (cadena.equals("=")) {
                texto = texto + cadena;
                if (st.hasMoreElements()) {
                    cadena = st.nextToken();
                    if (cadena.equals("=")) {
                        texto = texto + cadena + "\n";
                    } else if (!(cadena.equals(" ") || cadena.equals("\t"))) {
                        texto = texto + "\n" + cadena + "\n";
                    } else {
                        texto = texto + "\n";
                    }

                }
            } else if (cadena.equals(">") || cadena.equals("<")) {
                texto = texto + cadena;
                if (st.hasMoreElements()) {
                    cadena = st.nextToken();
                    if (cadena.equals("=")) {
                        texto = texto + cadena + "\n";
                    } else if (!(cadena.equals(" ") || cadena.equals("\t"))) {
                        texto = texto + "\n" + cadena + "\n";

                    } else {
                        texto = texto + "\n";
                    }
                }
            } else if (cadena.equals("\"")) {
                texto = texto + cadena;
                while (st.hasMoreElements()) {
                    cadena = st.nextToken();
                    if (cadena.equals("\"")) {
                        texto = texto + cadena + "\n";
                        break;
                    }
//                    if (cadena.equals(" ") || cadena.equals("\t")) {
//                        cadena = "";
//                    }
                    texto = texto + cadena;
                }
            } else if (cadena.equals(" ") || cadena.equals("\t")) {
                cadena = "";
            } else {
                texto = texto + cadena + "\n";
            }

        }
//        String txt1=texto;
        StringTokenizer st2 = new StringTokenizer(texto, "\n\r\f");
        texto = "";
        Lexico obLex2 = new Lexico();
        vecSal = new int[st2.countTokens() + 1];
        int i = 0;
        while (st2.hasMoreElements()) {
            obLex2 = obLex2.Etiquetar(st2.nextToken());
            texto = texto + "\n" + obLex2.lexema + "\t" + obLex2.nombre + "\t" + obLex2.numero;
            vecSal[i] = obLex2.numero;
            i++;
        }
        vecSal[vecSal.length - 1] = 53;
        jTProgramaCompilado.setText(texto);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbLexicoMouseClicked

    private void lbSintacticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSintacticoMouseClicked
        pnSemantico.setVisible(true);
        pnIntermedio.setVisible(false);
        pnOptimizacion.setVisible(false);
        pnObjeto.setVisible(false);

        String cadena = "";
        for (int i = 0; i < vecSal.length; i++) {
            cadena = cadena + vecSal[i] + " ";
        }
        cadena += "$";
        jTProgramaCompilado.setText(cadena);
        jLabel1.setText("Movimiento");
        jLabel2.setText("Cadena a validar");
        jTProgramaFuente.setText("$ 150");
        int mg[][] = {{},
        {159, 8, 150, 7, 6, 152, 5, 3},
        {8, 150, 7, 4},
        {},
        {153, 157, 14, 157},
        {152, 13},
        {},
        {18, 52, 10},
        {18, 156, 22, 52},
        {160, 52},
        {160, 51},
        {160, 50},
        {52},
        {51},
        {50},
        {154},
        {164},
        {162},
        {158},
        {155},
        {165},
        {150, 151},
        {},
        {160, 157, 161},
        {},
        {12},
        {21},
        {18, 6, 163, 157, 5, 1},
        {163, 157, 21},
        {},
        {18, 6, 52, 5, 2},
        {8, 150, 7, 6, 166, 50, 17, 50, 5, 9},
        {50, 16},
        {}
        };
        int mt[][] = new int[17][54];
        for (int i = 0; i < 17; i++) {
            for (int j = 0; j < 53; j++) {
                mt[i][j] = -1;
            }
        }
        mt[8][3] = 1;
        mt[9][1] = 3;
        mt[9][2] = 3;
        mt[9][3] = 3;
        mt[9][4] = 2;
        mt[9][8] = 3;
        mt[9][9] = 3;
        mt[9][10] = 3;
        mt[9][52] = 3;
        mt[9][53] = 3;
        mt[2][50] = 4;
        mt[2][51] = 4;
        mt[2][52] = 4;
        mt[3][6] = 6;
        mt[3][13] = 5;
        mt[4][10] = 7;
        mt[5][52] = 8;
        mt[6][50] = 11;
        mt[6][51] = 10;
        mt[6][52] = 9;
        mt[7][50] = 14;
        mt[7][51] = 13;
        mt[7][52] = 12;
        mt[1][1] = 17;
        mt[1][2] = 16;
        mt[1][3] = 18;
        mt[1][9] = 20;
        mt[1][10] = 15;
        mt[1][52] = 19;
        mt[0][1] = 21;
        mt[0][2] = 21;
        mt[0][3] = 21;
        mt[0][8] = 22;
        mt[0][9] = 21;
        mt[0][10] = 21;
        mt[0][52] = 21;
        mt[0][53] = 22;
        mt[10][12] = 23;
        mt[10][18] = 24;
        mt[10][21] = 23;
        mt[11][12] = 25;
        mt[11][21] = 26;
        mt[12][1] = 27;
        mt[13][6] = 29;
        mt[13][21] = 28;
        mt[14][2] = 30;
        mt[15][9] = 31;
        mt[16][16] = 32;
        mt[16][6] = 33;

        int vecMov[] = {0, 150};
        int vecMovAux[];
        int i = 0;
        int pr = 0;
        int pc = 0;
        int nl = 0;
        int tv = 0;
        cadena = "";

        do {
            pr = vecMov[vecMov.length - 1];
            if (pr >= 150) {
                pr = pr - 150;
                pc = vecSal[i];
                nl = mt[pr][pc];
                if (nl != -1) {
                    vecMovAux = vecMov;
                    vecMov = new int[(vecMovAux.length + mg[nl].length) - 1];
                    tv = 0;
                    for (int j = 0; j < vecMovAux.length - 1; j++) {
                        vecMov[j] = vecMovAux[j];
                    }
                    for (int j = vecMovAux.length - 1; j < vecMov.length; j++) {
                        vecMov[j] = mg[nl][tv];
                        tv++;
                    }
                    cadena = jTProgramaFuente.getText() + "\n";
                    for (int j = 0; j < vecMov.length; j++) {
                        cadena = cadena + vecMov[j] + " ";
                    }
                    jTProgramaFuente.setText(cadena);
                    cadena = jTProgramaCompilado.getText() + "\n";
                    for (int j = i; j < vecSal.length - 1; j++) {
                        cadena = cadena + vecSal[j] + " ";
                    }
                    cadena = cadena + "$";
                    jTProgramaCompilado.setText(cadena);
                } else {
                    cadena = jTProgramaFuente.getText() + "\n Error sintactico al recibirrr " + vecSal[i] + "se esperaba";
                    for (int j = 0; j < 54; j++) {
                        if (mt[pr][j] != -1) {
                            cadena = cadena + j + " ";
                        }
                    }
                    jTProgramaFuente.setText(cadena);
                    break;
                }
            } else {
                if (vecSal[i] == vecMov[vecMov.length - 1]) {
                    i++;
                    vecMovAux = vecMov;
                    vecMov = new int[vecMovAux.length - 1];
                    for (int j = 0; j < vecMov.length; j++) {
                        vecMov[j] = vecMovAux[j];
                    }
                    cadena = jTProgramaFuente.getText() + "\n";
                    for (int j = 0; j < vecMov.length; j++) {
                        cadena = cadena + vecMov[j] + " ";
                    }
                    jTProgramaFuente.setText(cadena);

                    cadena = jTProgramaCompilado.getText() + "\n";
                    for (int j = i; j < vecSal.length - 1; j++) {
                        cadena = cadena + vecSal[j] + " ";
                    }
                    cadena = cadena + "$";
                    jTProgramaCompilado.setText(cadena);
                } else {
                    if (vecSal[i] == 53 && vecMov[vecMov.length - 1] == 0) {
                        break;
                    }
                    int n = 0;
                    Lexico obLex = new Lexico();
                    while (n < obLex.dic.length) {
                        if (Integer.toString(vecSal[i]).equals(obLex.dic[n][2])) {
                            obLex.nombre = obLex.dic[n][1];
                            break;
                        } else if (vecSal[i] == 50) {
                            obLex.nombre = "Numerico";
                            break;
                        } else if (vecSal[i] == 51) {
                            obLex.nombre = "Cadena";
                            break;
                        } else if (vecSal[i] == 52) {
                            obLex.nombre = "Variable";
                            break;
                        }
                        n++;
                    }
                    cadena = jTProgramaFuente.getText() + "\nError sintactico al recibir: " + obLex.nombre;
                    n = 0;
                    obLex.nombre = "";
                    while (n < obLex.dic.length) {
                        if (Integer.toString(vecMov[vecMov.length - 1]).equals(obLex.dic[n][2])) {
                            obLex.nombre = obLex.dic[n][1];
                            break;
                        } else if (vecMov[vecMov.length - 1] == 50) {
                            obLex.nombre = "Numerico";
                            break;
                        } else if (vecMov[vecMov.length - 1] == 51) {
                            obLex.nombre = "Cadena";
                            break;
                        } else if (vecMov[vecMov.length - 1] == 52) {
                            obLex.nombre = "Variable";
                            break;
                        }
                        n++;
                    }
                    if (!obLex.nombre.equals("")) {
                        cadena = cadena + "\nSe esperaba: " + obLex.nombre;

                    }
                    jTProgramaFuente.setText(cadena);
                    break;
                }

            }
        } while (i < vecSal.length);
        if (vecMov[vecMov.length - 1] == 0 && !jTProgramaFuente.getText().contains("Error")) {
            cadena = jTProgramaFuente.getText() + "\nSintacticamente Correcto";
            jTProgramaFuente.setText(cadena);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSintacticoMouseClicked

    private void lbSemanticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSemanticoMouseClicked
        pnIntermedio.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSemanticoMouseClicked

    private void lbIntermedioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIntermedioMouseClicked
        pnOptimizacion.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbIntermedioMouseClicked

    private void lbOptimizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOptimizacionMouseClicked
        pnObjeto.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbOptimizacionMouseClicked

    private void lbCargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCargarMouseClicked
        pnSintactico.setVisible(false);
        pnSemantico.setVisible(false);
        pnIntermedio.setVisible(false);
        pnOptimizacion.setVisible(false);
        pnObjeto.setVisible(false);
        // TODO add your handling code here:
        jTProgramaFuente.setText(ManejoArchivos.cargarArchivo());
    }//GEN-LAST:event_lbCargarMouseClicked

    private void lbGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGuardarMouseClicked
        try {
            ManejoArchivos.guardarArchivo(jTProgramaFuente.getText());
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Archivo Guardado con exito.");
    }//GEN-LAST:event_lbGuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTProgramaCompilado;
    private javax.swing.JTextArea jTProgramaFuente;
    private javax.swing.JLabel lbCargar;
    private javax.swing.JLabel lbGuardar;
    private javax.swing.JLabel lbIntermedio;
    private javax.swing.JLabel lbLexico;
    private javax.swing.JLabel lbObjeto;
    private javax.swing.JLabel lbOptimizacion;
    private javax.swing.JLabel lbSemantico;
    private javax.swing.JLabel lbSintactico;
    private javax.swing.JPanel pnCarga1;
    private javax.swing.JPanel pnContenedor;
    private javax.swing.JPanel pnGuardar;
    private javax.swing.JPanel pnIntermedio;
    private javax.swing.JPanel pnLexico;
    private javax.swing.JPanel pnObjeto;
    private javax.swing.JPanel pnOptimizacion;
    private javax.swing.JPanel pnSemantico;
    private javax.swing.JPanel pnSintactico;
    // End of variables declaration//GEN-END:variables
}
